"""scripts/baselines/gen_locked_holdout_counts.py — ONE-TIME generator for
``_repro/LOCKED_HOLDOUT/_counts.json`` (RI mechanical remediation 2026-07-12, item 5; forensic
finding 续15 P0-2: "census len() 读 test_ids 与 ACCESS_LOG 矛盾坐实").

Why this exists: ``scripts/baselines/locked_rerun_cells.py``'s ``print_census()`` used to open
EVERY ``_repro/LOCKED_HOLDOUT/<dataset>.json`` manifest and call
``len(manifest.get("test_ids"/"dev_ids", []))`` to print a cell-count estimate. That call
materializes the full plaintext ``test_ids`` list into memory to take its length — it DOES read
``test_ids``, contradicting this directory's own ``ACCESS_LOG.md``, whose most recent entry (before
this remediation) claimed "test_ids NOT read (only len() counts via census)". That claim was
inaccurate; see the ACCESS_LOG.md correction entry appended alongside this fix.

The honest fix (per the remediation plan): the routine census path should never need to open a
manifest containing plaintext ``test_ids`` at all. Every ``_repro/LOCKED_HOLDOUT/<dataset>.json``
manifest ALREADY carries its own ``n_test``/``n_dev`` integer count fields (stamped at
``locked_split.py`` generation time — see ``kb_schema``-adjacent ``SourceManifest`` docstring
conventions for the general pattern), so no NEW count computation is even needed. This script:

  1. reads every manifest EXACTLY ONCE (this is the one, explicitly logged, reconciliation read —
     see the ACCESS_LOG.md entry this run's execution corresponds to);
  2. verifies each manifest's stamped ``n_test``/``n_dev`` matches ``len(test_ids)``/``len(dev_ids)``
     (an integrity check — if a manifest were ever hand-edited or corrupted this would catch it);
  3. writes a NEW small sidecar, ``_repro/LOCKED_HOLDOUT/_counts.json``, containing ONLY
     ``{dataset: {n_test, n_dev}}`` for every dataset key — no plaintext IDs of any kind.

After this one-time run, ``locked_rerun_cells.py.print_census()`` reads ONLY this sidecar (never
opening a per-dataset manifest's ``test_ids``/``dev_ids`` again for a routine census). A genuine
re-generation of this sidecar (e.g. after ``locked_split.py`` regenerates a manifest) is itself a
new, logged read — run this script again and log it.

Run (no GPU/network needed; pure stdlib):
    cd projects/speech-mllm-training-free-rl
    python scripts/baselines/gen_locked_holdout_counts.py
"""
from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
LOCKED_DIR = REPO_ROOT / "_repro" / "LOCKED_HOLDOUT"
OUT_PATH = LOCKED_DIR / "_counts.json"

# Files in this directory that are NOT a per-dataset manifest (mirrors
# locked_rerun_cells.locked_dataset_keys' exclusion list, plus the sidecar this script itself
# writes, so a re-run never tries to treat its own prior output as a "dataset").
NON_MANIFEST_STEMS = {"README", "ACCESS_LOG", "_counts"}


def main() -> int:
    if not LOCKED_DIR.is_dir():
        raise SystemExit(f"no {LOCKED_DIR} directory -- run locked_split.py first")

    counts: dict[str, dict] = {}
    mismatches: list[str] = []
    for p in sorted(LOCKED_DIR.glob("*.json")):
        if p.stem in NON_MANIFEST_STEMS:
            continue
        manifest = json.loads(p.read_text(encoding="utf-8"))
        n_test = manifest.get("n_test")
        n_dev = manifest.get("n_dev")
        # Integrity check ONLY -- this is the one explicitly-logged read of the plaintext id lists
        # this script performs; every FUTURE census read goes through _counts.json instead.
        actual_n_test = len(manifest.get("test_ids", []))
        actual_n_dev = len(manifest.get("dev_ids", []))
        if n_test != actual_n_test or n_dev != actual_n_dev:
            mismatches.append(
                f"{p.stem}: manifest n_test/n_dev={n_test}/{n_dev} != "
                f"len(test_ids)/len(dev_ids)={actual_n_test}/{actual_n_dev}"
            )
            # Fall back to the actual lengths so the sidecar is never wrong even if a manifest's
            # stamped count field is stale -- but the mismatch is still reported loudly below.
            n_test, n_dev = actual_n_test, actual_n_dev
        counts[p.stem] = {"n_test": n_test, "n_dev": n_dev}

    if mismatches:
        print("WARNING: n_test/n_dev field mismatches found (using recomputed lengths for these):",
              flush=True)
        for m in mismatches:
            print(f"  {m}", flush=True)

    out = {
        "_comment": (
            "Sidecar count-only cache for _repro/LOCKED_HOLDOUT/ census reporting (RI item 5, "
            "2026-07-12). Contains ONLY integer counts -- no plaintext test_ids/dev_ids of any "
            "kind. Generated by scripts/baselines/gen_locked_holdout_counts.py, which is the ONLY "
            "script that should ever read this directory's manifests for their id-list content; "
            "locked_rerun_cells.py's census reads THIS file instead."
        ),
        "counts": counts,
        "n_datasets": len(counts),
        "mismatches": mismatches,
    }

    LOCKED_DIR.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=str(LOCKED_DIR), prefix="_counts.json.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(out, handle, ensure_ascii=False, indent=2)
        os.replace(tmp_name, str(OUT_PATH))
    except Exception:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise

    print(f"wrote {OUT_PATH} ({len(counts)} dataset keys, {len(mismatches)} mismatches)", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
