"""scripts/baselines/locked_rerun_cells.py — LOCKED-HOLDOUT confirmatory rerun driver (ticket
#26 task 5). **PREP ONLY — this module is written and reviewable but NOT invoked by this ticket.**
See ``scripts/baselines/run_locked_rerun.sh``'s "DO NOT RUN" instruction; no GPU session is
acquired and no cell is generated by writing/reviewing this file.

## What this is a clone of

Structurally mirrors ``scripts/baselines/redraw_cells.py`` (the disjoint-redraw rerun driver) --
same census/archive/run_cell/run_all shape, same ``run_baseline.run_one``/``write_result``-adjacent
reuse discipline -- pointed at ``_repro/LOCKED_HOLDOUT/`` manifests instead of
``_repro/redraw_manifest.json``, single backbone (``qwen3-omni-30b-gguf`` only, owner ruling
Decision-Log 续13), ``slice_mode="locked-group"`` (see ``run_baseline._load_rows_locked``).

## The ONE thing that must NOT be copied from redraw_cells.py (RI-G0)

``redraw_cells.py`` reruns a cell **in place** under the SAME artifact id
(``<dataset>__<backbone>__<split>.json``) once its id-set no longer matches the frozen manifest,
archiving the PRE-redraw file as a `.pre-redraw-20260710.json` sidecar first. That in-place-
overwrite pattern is explicitly forbidden here (ticket #26 task 5, RI-G0 rule -- see
`c2691f8`'s "aishell disjoint run moved to NEW artifact ID (in-place overwrite reverted per
RI-G0)"): a locked-rerun cell writes to a **brand-new artifact id**,
``<dataset>__qwen3-omni-30b-gguf__{dev,test}.locked.json`` -- distinct from BOTH the original
seeded cell and any disjoint-redraw cell -- and **refuses to overwrite** that new artifact id if
it already exists (``run_cell`` skips with a loud message instead; a genuine re-generation needs a
human to archive/rename the existing `.locked.json` first). The CURRENT (pre-locked-rerun) plain
`.json` cell is still archived as a `.pre-lockedrerun-20260711.json` sidecar for provenance, same
append-only idempotent discipline as ``redraw_cells.archive_old`` -- but that archiving is
ancillary bookkeeping, never the thing this driver overwrites.

Usage (once actually run -- NOT by this ticket):
  python locked_rerun_cells.py --census                                   # read-only rerun/skip table
  python locked_rerun_cells.py --dry-run                                  # alias for --census
  python locked_rerun_cells.py --execute --dataset aishell-1 --split dev --parallel 4
                                                                            # ONE cell (validation)
  python locked_rerun_cells.py --execute --parallel 4                     # every LOCKED_HOLDOUT key
                                                                            # (needs GPU session +
                                                                            # resident qwen3 server up)
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))            # scripts/baselines

import run_baseline as rb             # noqa: E402  (reuses run_one/OUT_DIR -- NOT write_result, see below)

REPO_ROOT = Path(__file__).resolve().parents[2]
LOCKED_DIR = REPO_ROOT / "_repro" / "LOCKED_HOLDOUT"

BACKBONE = "qwen3-omni-30b-gguf"          # single-backbone rerun scope (owner ruling, Decision-Log 续13)
SPLITS = ("dev", "test")
ARCHIVE_TAG = "pre-lockedrerun-20260711"   # append-only archive suffix for the CURRENT plain cell

# Per-generation wall-clock estimate (seconds/item) -- reused verbatim from wave1_cells.GEN_TIME_S /
# redraw_cells.GEN_TIME_S (same qwen3-omni-30b-gguf generation path via run_baseline.generate).
GEN_TIME_S = 2.8
BATCH_SPEEDUP = 1.75   # owner-approved smoke verdict (see wave3_cells.py) -- used only for the estimate


def locked_dataset_keys() -> list[str]:
    """Every dataset key with a ``_repro/LOCKED_HOLDOUT/<key>.json`` manifest -- the rerun scope
    (whatever ``locked_split.py`` has generated so far; NOT hardcoded to the ~65 redraw-scope
    list, so this driver naturally covers however many manifests actually exist on disk)."""
    if not LOCKED_DIR.is_dir():
        return []
    return sorted(p.stem for p in LOCKED_DIR.glob("*.json")
                  if p.stem not in ("README", "ACCESS_LOG"))


def plain_result_path(dataset: str, split: str) -> Path:
    """The ORIGINAL (pre-existing, non-locked) result cell -- read-only reference point for
    ``archive_old`` below, never written here."""
    return rb.OUT_DIR / f"{dataset}__{BACKBONE}__{split}.json"


def locked_result_path(dataset: str, split: str) -> Path:
    """The NEW artifact id this driver writes to (ticket #26 task 5) -- distinct from
    ``plain_result_path`` AND from ``redraw_cells.locked``... er, from
    ``redraw_cells.result_path``'s in-place-overwritten id. Never the same path as either."""
    return rb.OUT_DIR / f"{dataset}__{BACKBONE}__{split}.locked.json"


def archive_path(dataset: str, split: str) -> Path:
    return rb.OUT_DIR / f"{dataset}__{BACKBONE}__{split}.{ARCHIVE_TAG}.json"


def archive_old(dataset: str, split: str) -> Path | None:
    """Copy the CURRENT plain result JSON (if any) to its own append-only archive sidecar --
    mirrors ``redraw_cells.archive_old`` exactly (idempotent: a no-op if the archive already
    exists, so a re-invocation after a partial failure can never clobber the ORIGINAL pre-
    locked-rerun content). This is provenance bookkeeping ONLY -- the locked-rerun result itself
    goes to ``locked_result_path``, a different file entirely, never this one."""
    p = plain_result_path(dataset, split)
    if not p.exists():
        return None
    ap = archive_path(dataset, split)
    if not ap.exists():
        shutil.copy2(p, ap)
    return ap


def needs_run(dataset: str, split: str) -> tuple[bool, str]:
    """(need_run, reason). Unlike ``redraw_cells.needs_rerun`` (which compares id-SETS to decide
    whether an in-place rerun is needed), the locked-rerun checkpoint is simply "does the NEW
    artifact id already exist" -- RI-G0 means this driver never overwrites it once written, so
    existence alone is the complete checkpoint signal."""
    if not (LOCKED_DIR / f"{dataset}.json").exists():
        return False, "no-locked-manifest"
    if locked_result_path(dataset, split).exists():
        return False, "locked-artifact-already-exists"
    return True, "no-locked-artifact-yet"


def all_cells() -> list[tuple[str, str]]:
    return [(dk, sp) for dk in locked_dataset_keys() for sp in SPLITS]


def print_census(parallel: int = 4) -> None:
    cells = all_cells()
    rep = {(dk, sp): needs_run(dk, sp) for dk, sp in cells}
    n_run = sum(1 for v in rep.values() if v[0])
    n_skip = len(cells) - n_run

    print(f"=== locked-rerun census: {len(locked_dataset_keys())} LOCKED_HOLDOUT dataset key(s) "
          f"x {len(SPLITS)} splits = {len(cells)} cells (backbone={BACKBONE} only) ===\n")
    for dk in locked_dataset_keys():
        parts = []
        for sp in SPLITS:
            need, reason = rep[(dk, sp)]
            tag = "RUN" if need else "skip"
            parts.append(f"{sp}={tag}({reason})")
        print(f"  {dk:45s} {'  '.join(parts)}")

    total_n = 0
    for dk, sp in cells:
        if rep[(dk, sp)][0]:
            try:
                manifest = json.loads((LOCKED_DIR / f"{dk}.json").read_text(encoding="utf-8"))
                total_n += len(manifest.get("test_ids" if sp == "test" else "dev_ids", []))
            except (OSError, json.JSONDecodeError):
                pass
    secs_seq = total_n * GEN_TIME_S
    secs_batch = secs_seq / BATCH_SPEEDUP if parallel > 1 else secs_seq
    print(f"\nTOTAL: {n_run} cell(s) need a run, {n_skip} cell(s) skip, of {len(cells)}.")
    print(f"estimated item count to generate: {total_n}; wall-clock sequential "
          f"{secs_seq / 60:.1f} min, batched --parallel {parallel}: {secs_batch / 60:.1f} min "
          f"({BATCH_SPEEDUP}x smoke-measured speedup)")


def run_cell(dataset: str, split: str, parallel: int = 4, skip_checkpoint: bool = True) -> dict | None:
    """Run exactly one locked-rerun cell via ``run_baseline.run_one(..., slice_mode="locked-group")``
    -- NOT ``run_baseline.write_result`` (that writes the PLAIN artifact id; this driver writes its
    own NEW ``.locked.json`` id directly, see ``locked_result_path``). NEVER raises -- catches and
    logs, mirroring redraw_cells.run_cell's own per-cell guard.

    RI-G0: refuses to overwrite an existing ``.locked.json`` (the whole point of the new artifact
    id) -- ``skip_checkpoint=True`` (default) makes that refusal the normal, silent-if-already-done
    behavior; pass ``skip_checkpoint=False`` (``--no-checkpoint``) to force a genuine re-generation
    ONLY after manually archiving/renaming the existing file (this driver will still refuse to
    overwrite even then -- see the hard guard below; ``--no-checkpoint`` only skips the "quietly
    treat as already done" short-circuit, it does not disable RI-G0 itself).
    """
    lp = locked_result_path(dataset, split)
    need, reason = needs_run(dataset, split)
    if skip_checkpoint and not need:
        print(f"  [skip] {dataset}/{BACKBONE}/{split}: {reason}", flush=True)
        return None
    if lp.exists():
        # RI-G0 hard guard: even under --no-checkpoint, this driver NEVER overwrites an existing
        # locked artifact -- the redraw runner's in-place-overwrite pattern must not be copied here
        # under ANY flag combination. A genuine re-generation requires archiving/renaming lp first.
        print(f"  [refuse] {lp} already exists -- RI-G0: this driver never overwrites a locked "
              "artifact; archive/rename it first if a genuine re-generation is wanted.", flush=True)
        return None

    archived = archive_old(dataset, split)
    if archived:
        print(f"  archived pre-locked-rerun JSON -> {archived}", flush=True)
    print(f"=== locked-rerun cell: {dataset} / {BACKBONE} / {split} (parallel={parallel}) ===", flush=True)
    try:
        result = rb.run_one(dataset, BACKBONE, split, None, parallel=parallel, slice_mode="locked-group")
    except Exception as e:  # noqa: BLE001 -- one bad cell must not sink the whole locked-rerun sweep
        print(f"  !! {dataset}/{split} FAILED: {type(e).__name__}: {e}", flush=True)
        return None

    lp.parent.mkdir(parents=True, exist_ok=True)
    json.dump(result, open(lp, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    agg = result["aggregate"]
    print(f"  wrote {lp} (mean={agg['mean']} ci={agg['ci95']} n_scored={agg['n_scored']}/{agg['n_total']} "
          f"elapsed_s={result['elapsed_s']} parallel={parallel})", flush=True)
    return result


def run_all(only_dataset: str | None = None, only_split: str | None = None,
            parallel: int = 4, skip_checkpoint: bool = True) -> dict:
    """Iterate every (dataset, split) cell with a LOCKED_HOLDOUT manifest (or the one selected by
    ``only_dataset``/``only_split``). Assumes the GPU lock is already held and the resident
    qwen3-omni-30b-gguf llama-server is already up (see run_locked_rerun.sh) -- mirrors
    redraw_cells.run_all's {ran, skipped, failed, total} exit-code contract exactly."""
    cells = all_cells()
    if only_dataset:
        assert (LOCKED_DIR / f"{only_dataset}.json").exists(), (
            f"{only_dataset!r} has no _repro/LOCKED_HOLDOUT/{only_dataset}.json manifest -- run "
            "locked_split.py first"
        )
        cells = [(dk, sp) for dk, sp in cells if dk == only_dataset]
    if only_split:
        cells = [(dk, sp) for dk, sp in cells if sp == only_split]

    t0 = time.time()
    n_ran = n_skipped = n_failed = 0
    for dk, sp in cells:
        before_need, _ = needs_run(dk, sp)
        result = run_cell(dk, sp, parallel=parallel, skip_checkpoint=skip_checkpoint)
        if result is not None:
            n_ran += 1
        elif not before_need:
            n_skipped += 1
        else:
            n_failed += 1
    print(f"=== locked-rerun done in {time.time() - t0:.0f}s "
          f"(ran={n_ran} skipped={n_skipped} failed={n_failed} of {len(cells)}) ===", flush=True)
    # Machine-parseable twin -- run_locked_rerun.sh greps this exact prefix, mirrors REDRAW_SUMMARY.
    print(f"LOCKED_RERUN_SUMMARY ran={n_ran} skipped={n_skipped} failed={n_failed} total={len(cells)}",
          flush=True)
    return {"ran": n_ran, "skipped": n_skipped, "failed": n_failed, "total": len(cells)}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dataset", default=None, help="restrict to one dataset key (default: all LOCKED_HOLDOUT keys)")
    ap.add_argument("--split", choices=SPLITS, default=None, help="restrict to one split (default: both)")
    ap.add_argument("--census", action="store_true", help="read-only run/skip table; no GPU/model calls")
    ap.add_argument("--dry-run", action="store_true", help="alias for --census")
    ap.add_argument("--execute", action="store_true",
                     help="actually run cells -- requires the GPU session held + the resident "
                          "qwen3-omni-30b-gguf llama-server already up (see run_locked_rerun.sh). "
                          "**NOT invoked by ticket #26 -- prep only.**")
    ap.add_argument("--no-checkpoint", action="store_true",
                     help="don't silently skip a cell whose .locked.json already exists via the "
                          "quiet checkpoint path -- RI-G0's hard overwrite guard still applies "
                          "regardless (see run_cell's docstring)")
    ap.add_argument("--parallel", type=int, default=4,
                     help="client-side concurrent HTTP requests per cell (default 4, matches the "
                          "resident server's -np slot count)")
    args = ap.parse_args()

    if args.census or args.dry_run or not args.execute:
        print_census(parallel=args.parallel)
        return

    summary = run_all(only_dataset=args.dataset, only_split=args.split,
                       parallel=args.parallel, skip_checkpoint=not args.no_checkpoint)
    if summary["failed"] > 0:
        print(f"ERROR: locked_rerun_cells.py --execute: {summary['failed']} cell(s) failed -- see "
              "FAILED lines above.", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
