"""Genuine training-free-RL best-of-N ASR via llama.cpp (Qwen3-Omni-30B GGUF, resident llama-server).

This is the REAL reward-driven best-of-N the project's thesis needs: sample N transcripts from a
*frozen* generative omni model (no weight change) and SELECT among them with a verifiable reward.
Two selectors, exactly as the theory distinguishes them:
  - MBR consensus (reference-free, utility = -WER between candidates) = the DEPLOYABLE selector
    (uses no labels at inference; a genuine training-free-RL move);
  - oracle best-of-N (reward = -WER vs the reference) = the headroom UPPER BOUND (not deployable).
Reports greedy WER, per-N WER, and paired-bootstrap CIs on the per-utterance WER reduction, and
commits an artifact + reproduce command.

Candidates are generated by driving Qwen3-Omni-30B-A3B (Q8_0 GGUF + mmproj) through a resident
llama.cpp `llama-server` (audio via the OpenAI-compatible `input_audio` content). NOTE: llama.cpp
audio input is flagged EXPERIMENTAL upstream ("may have reduced quality") — reported honestly.

Start the server first (one load, ~4 min):
  LD_LIBRARY_PATH=~/llama.cpp/build/bin ~/llama.cpp/build/bin/llama-server \
    -m <gguf-dir>/Qwen3-Omni-30B-A3B-Instruct-Q8_0.gguf \
    --mmproj <gguf-dir>/mmproj-Qwen3-Omni-30B-A3B-Instruct-bf16.gguf \
    -ngl 28 -c 8192 --host 127.0.0.1 --port 8091 --no-warmup
reproduce:
  SPEECHRL_DATA_DIR=/mnt/e/chao_workspace/exploring-l4-intelligence/speechrl-data BON_UTTS=96 BON_POOL=8 BON_TEMP=0.8 BON_SNR=5 \
    ~/.venvs/speechrl/bin/python scripts/repro_asr_best_of_n_llamacpp.py
"""
import base64, json, os, sys, time, urllib.request
from pathlib import Path
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from repro_asr_best_of_n import load_utts, INSTRUCTION  # reuse manifest/refs + prompt
sys.path.insert(0, "/mnt/d/chao_workspace/exploring-l4-intelligence/common/src")
from speechrl_common.rl.decode import best_of_n, mbr
from speechrl_common.rl.reward import wer

BASE = os.environ.get("LLAMA_SERVER", "http://127.0.0.1:8091")
DATA = os.environ["SPEECHRL_DATA_DIR"]
N_UTTS = int(os.environ.get("BON_UTTS", "24"))
POOL = int(os.environ.get("BON_POOL", "8"))
TEMP = float(os.environ.get("BON_TEMP", "0.8"))
SNR = float(os.environ.get("BON_SNR", "5"))
SEED = int(os.environ.get("BON_SEED", "42"))
MAXTOK = int(os.environ.get("BON_MAXTOK", "100"))
NBOOT = int(os.environ.get("BON_NBOOT", "2000"))
Ns = [n for n in (1, 2, 4, 8) if n <= POOL]
OUT = Path(DATA) / "_repro" / "asr_bon_llamacpp_snr5.json"


def _post(payload):
    req = urllib.request.Request(BASE + "/v1/chat/completions", data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=300) as r:
        return json.loads(r.read().decode())["choices"][0]["message"]["content"].strip()


def gen(clip, greedy, seed):
    b64 = base64.b64encode(open(clip, "rb").read()).decode()
    payload = {"messages": [{"role": "user", "content": [
        {"type": "input_audio", "input_audio": {"data": b64, "format": "wav"}},
        {"type": "text", "text": INSTRUCTION}]}],
        "max_tokens": MAXTOK, "seed": seed,
        "temperature": 0.0 if greedy else TEMP}
    if not greedy:
        payload["top_p"] = 0.95
    return _post(payload)


def agg(rows, key):
    g = np.array([r["greedy_wer"] for r in rows]); s = np.array([r[key] for r in rows])
    red = g - s  # positive = WER improvement over greedy
    rng = np.random.default_rng(SEED); n = len(red); bs = np.empty(NBOOT)
    for i in range(NBOOT):
        bs[i] = red[rng.integers(0, n, n)].mean()
    lo, hi = float(np.quantile(bs, 0.025)), float(np.quantile(bs, 0.975))
    return round(float(s.mean()), 4), round(float(red.mean()), 4), [round(lo, 4), round(hi, 4)], bool(lo > 0)


def main():
    t0 = time.time()
    # BON_SEEDS: multiple generation seeds pooled into ONE paired bootstrap, so the CI reflects both
    # per-utterance AND pool-generation variance (each seed = an independent utt-sample + generation draw).
    seeds = [int(x) for x in os.environ.get("BON_SEEDS", str(SEED)).split(",")]
    print(f"server={BASE} seeds={seeds} utts/seed={N_UTTS} pool={POOL} temp={TEMP} snr={SNR} Ns={Ns}", flush=True)
    rows = []
    for s in seeds:
        utts = load_utts(DATA, "other", N_UTTS, s, SNR)
        for k, u in enumerate(utts):
            try:
                greedy = gen(u["audio_path"], True, s)
                pool = [gen(u["audio_path"], False, s + 1 + i) for i in range(POOL)]
            except Exception as e:
                print(f"  seed {s} [{k+1}] SKIP ({type(e).__name__}: {str(e)[:100]})", flush=True); continue
            rec = {"gen_seed": s, "id": u["id"], "ref": u["ref"], "greedy": greedy,
                   "greedy_wer": wer(u["ref"], greedy), "pool": pool}
            for N in Ns:
                cand = pool[:N]
                rec[f"oracle_wer_{N}"] = wer(u["ref"], best_of_n(cand, lambda c: -wer(u["ref"], c))["best"])  # oracle headroom
                rec[f"mbr_wer_{N}"] = wer(u["ref"], mbr(cand, lambda ci, cj: -wer(cj, ci))["best"])            # MBR (deployable)
            rows.append(rec)
        print(f"  seed {s}: cumulative rows={len(rows)}", flush=True)

    summary = {"n_utts": len(rows), "gen_seeds": seeds, "n_gen_seeds": len(seeds), "utts_per_seed": N_UTTS,
               "pool": POOL, "temp": TEMP, "snr_db": SNR, "Ns": Ns,
               "note": "rows pooled across generation seeds; the paired bootstrap CI reflects per-utterance AND pool-generation variance",
               "model": "qwen3-omni-30b-a3b-instruct Q8_0 GGUF (llama.cpp, -ngl 28; audio EXPERIMENTAL)",
               "greedy_wer": round(float(np.mean([r["greedy_wer"] for r in rows])), 4)}
    for N in Ns:
        summary[f"mbr_wer_{N}"], summary[f"mbr_red_{N}"], summary[f"mbr_ci_{N}"], summary[f"mbr_sig_{N}"] = agg(rows, f"mbr_wer_{N}")
        summary[f"oracle_wer_{N}"], summary[f"oracle_red_{N}"], summary[f"oracle_ci_{N}"], _ = agg(rows, f"oracle_wer_{N}")
    nmax = Ns[-1]
    summary["verdict"] = (
        f"Genuine training-free-RL best-of-N (Qwen3-Omni-30B, N={nmax}): greedy WER {summary['greedy_wer']:.3f}; "
        f"DEPLOYABLE MBR-consensus WER {summary[f'mbr_wer_{nmax}']:.3f} "
        f"(reduction {summary[f'mbr_red_{nmax}']:+.3f}, 95% CI {summary[f'mbr_ci_{nmax}']}, "
        f"{'SIG' if summary[f'mbr_sig_{nmax}'] else 'n.s.'}); oracle headroom WER "
        f"{summary[f'oracle_wer_{nmax}']:.3f} (reduction {summary[f'oracle_red_{nmax}']:+.3f}). "
        f"Reward-driven selection over model-sampled candidates on a frozen model; CI pooled across "
        f"{len(seeds)} generation seeds (utterance + pool-generation variance).")
    out = {"summary": summary, "per_utt": rows, "elapsed_s": round(time.time() - t0, 1),
           "reproduce": "SPEECHRL_DATA_DIR=/mnt/e/chao_workspace/exploring-l4-intelligence/speechrl-data BON_SEEDS=42,7,123 BON_UTTS=48 BON_POOL=8 BON_SNR=5 "
                        "python scripts/repro_asr_best_of_n_llamacpp.py (with llama-server resident)"}
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        json.dump(out, f, indent=2)
    print("\n=== SUMMARY ===\n" + json.dumps(summary, indent=2), flush=True)
    print("wrote", os.path.abspath(OUT), flush=True)
    print("ASR_BON_LLAMACPP_DONE", flush=True)


if __name__ == "__main__":
    main()
